<?php
global $URL_PATH; // Necesitamos la trayectoria de la URL a la app
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>
<?php /* El action es una ruta. Necesita el URL_PATH */?>
<form class="mt-4" action="<?=$URL_PATH?>/registro" method="POST">
    <div class="form-group row">
        <label for="login" class="col-md-2 col-form-label">Login</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="login" value="" name="login">
        </div>
    </div>
    <div class="form-group row">
        <label for="pass1" class="col-md-2 col-form-label">contraseña: </label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="pass1" value="" name="password">
        </div>
    </div>
    <div class="form-group row">
        <label for="pass2" class="col-md-2 col-form-label">repite: </label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="pass2" value="">
        </div>
    </div>
    <div class="form-group row">
        <label for="nombre" class="col-md-2 col-form-label">nombre</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="nombre" name="nombre" value="">
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-md-2 col-form-label">email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" name="email" value="">
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary offset-md-2">Registrarse!</button>
    </div>
</form>
<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>