<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        SocialDaw
        <?php \dawfony\Ti::endBlock(); ?>
    </title>
    <?php /* jquery cdn */ ?>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <?php /* Bootstrap. Las rutas deben ser absolutas, porque estamos haciendo rewrite */ ?>
    <link rel="stylesheet" href="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/css/bootstrap.css">
    <script src="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/js/bootstrap.js"></script>
    <?php /* Font awesome CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <?php /* Animate.css CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <?php /* Javascript de este proyecto */ ?>
    <script src="<?= $URL_PATH ?>/js/main.js"></script>
    <script>
        var URL_PATH = "<?= $URL_PATH ?>"; // Pasamos el URL_PATH de php a Javascript.
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Hammersmith+One&display=swap&subset=latin-ext');
        #mainjumbo.jumbotron {
            background-image: url('<?= $URL_PATH ?>/assets/background.jpg');
            background-size: cover;
            background-position: bottom;
            height: 100%;
        }
        .myfont {
            font-family: 'Hammersmith One', sans-serif; 
        }
    </style>
    <?php /*Para añadir lineas al head desde las plantillas derivadas*/ ?>
    <?php \dawfony\Ti::startBlock("head"); ?>
    <?php \dawfony\Ti::endBlock(); ?>
</head>

<body class="container">
    <div class="jumbotron shadow" id="mainjumbo">
        <div class="text-center myfont">
            <img class="img-fluid w-60" src="<?= $URL_PATH ?>/assets/logo.png" alt="sociadaw logo">
            <br>
            <h3><em>Tu red de anime, jpop y kpop</em></h3>
        </div> 

            

    </div>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-info sticky-top myfont">
        <a class="navbar-brand" href="<?= $URL_PATH ?>/">Lo último</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <?php if (!isset($_SESSION["login"])) : // no hay usuario logueado
                ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $URL_PATH ?>/registro">Registro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $URL_PATH ?>/login">Login</a>
                    </li>
                <?php else : // si hay usuario logueado
                ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $URL_PATH ?>/siguiendo">Siguiendo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $URL_PATH ?>/perfil/<?= $_SESSION["login"] ?>">Tu perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="confirmarLogout()">Cerrar sesión</a>
                    </li>
                <?php endif; ?>

            </ul>

            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>
    <?php \dawfony\Ti::startBlock("content"); ?>
    Bloque "content" en Main view.
    Sustituye en las clases que extiende.
    <?php \dawfony\Ti::endBlock(); ?>
    <footer class="rounded p-4 mt-2 text-center bg-light myfont">
        © <?= date("Y") ?> Copyright: socialdaw
    </footer>
</body>

</html>