<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
function convertYoutube($string) {
	return preg_replace(
		"/\s*[a-zA-Z\/\/:\.]*youtu(be.com\/watch\?v=|.be\/)([a-zA-Z0-9\-_]+)([a-zA-Z0-9\/\*\-\_\?\&\;\%\=\.]*)/i",
		"<iframe width=\"420\" height=\"315\" src=\"//www.youtube.com/embed/$2\" allowfullscreen></iframe>",
		$string
	);
}
?>

<div class="row m-2">
    <div class="col-5">
        <img class="img-fluid rounded" src="<?= $URL_PATH ?>/assets/foto/<?= $post->foto ?>" alt="Imagen: <?= $post->resumen ?>">
    </div>
    <div class="col-7">
        <h4><?= $post->resumen ?></h4>
        <div>
            <i class="fa fa-heart"></i> <?= $post->numLikes ?>
            <i class="fa fa-comments"></i> <?= $post->numComments ?>
        </div>
        <div>
            Por <a href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a>
            en <em><?= $post->categoria ?></em>
            el <?= $post->fecha ?>
        </div>
    </div>
</div>
<div class="container">
    <?= convertYoutube($post->texto) ?>
</div>
<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>