<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>

<div class="row m-2">
    <div class="col-5">
        <img class="img-fluid rounded" src="<?= $URL_PATH ?>/assets/foto/<?= $post->foto ?>" alt="Imagen: <?= $post->resumen ?>">
    </div>
    <div class="col-7">
        <h4><?= $post->resumen ?></h4>
        <div>
            <i class="fa fa-heart"></i> <?= $post->numLikes ?>
            <i class="fa fa-comments"></i> <?= $post->numComments ?>
        </div>
        <div>
            Por <a href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a>
            en <em><?= $post->categoria ?></em>
            el <?= $post->fecha ?>
        </div>
    </div>
</div>
<div class="container">
    <?= $post->texto ?>
</div>
<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>